### ISSUE TITLE
[BUG] Failed to load script...

### ISSUE THREAD

**Issue by skyejonke** [org-roam/org-roam-ui#91]
**Describe the bug**
I am trying to use org-roam-ui with spacemacs, following the manual installation instructions. However every time I run org-roam-ui mode it opens a webpage which is completely blank, and looking at the console commands it gives failed to load script errors, as well as 404 errors once I reload the page.

**To Reproduce**
1. M-x org-roam-ui-mode
2. Blank screen appears in browser

**Expected behavior**
Org-roam-ui-mode to open as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/29717600/134817755-e228897a-2036-489f-ac12-cf9c96b86309.png)

**What browser were you using?**
Firefox, but I get similar issues with chrome-based browsers.

**Additional context**
I tried in a fresh firefox profile, and tried removing all of the data associated with the page, but nothing changed. I also tried looking for the scripts it cannot seem to find, but I don't see them anywhere in my directory.

**Comment by prashantnag93** [comment]
@ThomasFKJorna Same Problem with my system. I am using ubuntu 20.04 and firefox92 and Emacs 28.50.

**Comment by liny01-nbsa** [comment]
@prashantnag93, @skyejonke, if you have `yarn` installed locally, you can try to run
```
yarn
yarn build
```

It works for me.

**Comment by ThomasFKJorna** [comment]
That's my bad, something went wrong with the build, don't know exactly what though. It should be fixed now!

**Comment by RobinKD** [comment]
I initially posted in #61 because issues were similar, but this one seems to be exactly the same.
I tried using commit 73a65738f7829c577ee27be2f3ca5e1cd1867cfd and the issue still seems to persist for me.
I tried debugging but don't get any error while enabling orui mode, so I have no idea what went wrong.
